import logging

from app.state.run_state import update_run_state

logger = logging.getLogger(__name__)

def make_condense_topic(get_llm):
    def condense_topic(state):
        """
        Condenses the topic of the outline from the initial user input and user feedback in the outline review to create a more specific topic that the research and writing will focus on. 
        This is important to ensure that the assistant is addressing the user's specific needs and feedback, rather than sticking too closely to an original topic which may be too broad, be altered through further revisions,
        or which may contain specific advice for the outline which will not be relevant to the research and writer subgraphs. 
        The condensed topic is generated by prompting an LLM with the original topic and the user's review comments, and asking it to generate a more specific topic that still relates to the original topic.
        Args:
            state: The current state of the graph, which includes the original topic and the user's review comment.
        Returns:
            A new state with the condensed topic and an updated status.
        """
        model = get_llm()
        original_topic = state.get("topic", "")
        request_messages = state.get("request_messages", [])


        logger.info("Condensing topic. Original topic: %s. User feedback: %s", original_topic, request_messages)
        
        
        prompt = f"""
        The original topic is: {original_topic}. Here is a list of messages the user has provided as feedback (may be blank): {request_messages}. 
        Your role is to generate a condensed version of the original topic that incorporates the user's feedback and is more specific, so that the research and writing can be focused on this condensed topic.
        Please provide a condensed version of the topic that is specific and incorporates the user's feedback, while still relating to the original topic.
        The purpose of this condensed topic is to guide the research and writing, so it should be specific enough to provide clear direction, but still broad enough to encompass the user's original intent and feedback.
        It also guides the Tavily API in finding relevant information, so it should be phrased in a way that is likely to match relevant sources of information.
        If the original topic is already specific, brief, and incorporates the user's feedback, you can return the original topic as the condensed topic.
        Please provide only the condensed topic in your response, with no additional explanation or formatting.
        Do not include any information not present in the original topic and user feedback, as the condensed topic should be based solely on those two inputs.
        """
        condensed_topic = ""
        result = model.invoke(prompt)
        if isinstance(result, str):
            condensed_topic = result
        else:
            condensed_topic = str(getattr(result, "content", result))
        
        
        logger.debug("Condensed topic generated by LLM: %s", condensed_topic)
        
        
        update_run_state(state.get("request_id", ""), topic=condensed_topic, status="Optimized topic for research and writing.", last_completed_node="condense_topic")
        return {
            "topic": condensed_topic,
            "status": "Optimized topic for research and writing."
        }
    return condense_topic