CREATE TABLE IF NOT EXISTS run_state (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    request_id TEXT UNIQUE,
    thread_id TEXT UNIQUE,
    topic TEXT,
    status TEXT,
    last_completed_node TEXT,
    error_message TEXT,
    request_messages JSONB,
    section_questions JSONB,
    current_outline TEXT,
    outline_object JSONB,
    outline_history JSONB,
    review_action TEXT,
    review_comment TEXT,
    final_report JSONB,
    validated_sources JSONB,
    candidate_sources JSONB,
    research_iteration INTEGER DEFAULT 0,
    research_done BOOLEAN DEFAULT FALSE,
    research_complete_by_section JSONB,
    writing_iteration INTEGER DEFAULT 0,
    writing_draft JSONB,
    writing_feedback JSONB,
    writing_done BOOLEAN DEFAULT FALSE,
    writing_complete_by_section JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_updated_at TIMESTAMPTZ DEFAULT NOW()
);